#!/usr/bin/env python3
# ots_federation/quickstart.py
# Console-script entry point: ots-federation-quickstart (pyproject.toml).
#
# PRECONDITION (NOT performed by this script — chicken-and-egg): the
# ots-federation wheel must already be `pip install`ed into the OTS venv.
# This script IS that wheel's own console-script entry point, so if it is
# running at all, the ots_federation package is already on this interpreter's
# path. What is NOT guaranteed is that the wheel's *dependencies* (chiefly
# `opentakserver` itself, declared in pyproject.toml) resolved correctly in
# this environment — e.g. the operator ran the wrong venv's console script,
# or installed with `pip install --no-deps`. _check_ots_environment() catches
# that case and prints the pip line as remediation (README.qmd "Plugin Fails
# to Load" documents the resulting OTS-side symptom).
#
# Workflow (idempotent; refuses to clobber existing output without --force):
#   1. sanity-check the OTS environment (opentakserver importable)
#   2. detect OTS install (config.yml, informational only — never edited)
#   3. ots-fed-certs generate  -> CA + SAN-correct server/client cert + chain
#   4. write a minimal federation.ini (documented wildcard defaults)
#   5. ots-fed-certs export    -> peer-exchange bundle (mutual-CA)
#   6. print the restart instruction
#
# Defaults mirror the live fleet convention (ansible ots_server role, main
# branch — read via `git show main:project_roles/ots_server/...` per
# workspace convention; this repo's working tree stays on its own branch,
# never switched or written to):
#   cert dir:            /opt/ots/fed_ssl               (ots_server_fed_ssl_dir)
#   federation.ini:      /opt/ots/config/federation.ini  (ots_server_federation_ini)
#   listen_port:         9101
#   accept_as / share_as: "*:__ANON__" / "__ANON__:__ANON__"
#                         (ots_server_federation_accept_as / _share_as)

import argparse
import os
import socket
import sys

from ots_federation.gen_fed_ca import cmd_export, cmd_generate

DEFAULT_CERT_DIR = "/opt/ots/fed_ssl"
DEFAULT_INI_PATH = "/opt/ots/config/federation.ini"
DEFAULT_OTS_CONFIG = "/opt/ots/config/config.yml"
DEFAULT_LISTEN_PORT = 9101
# Fleet-proven wildcard defaults (ansible ots_server role, main branch,
# project_roles/ots_server/defaults/main.yml) — permissive on purpose so a
# freshly quick-started node federates out of the box; TIGHTEN before adding
# real [federate:*] peers.
DEFAULT_ACCEPT_AS = "*:__ANON__"
DEFAULT_SHARE_AS = "__ANON__:__ANON__"

# Mirrors gen_fed_ca.py's `generate` output file set — used only to detect
# pre-existing output for the clobber guard, not to read/parse it.
_GENERATE_OUTPUT_FILES = (
    "fed-ca.key", "fed-ca.crt",
    "server.key", "server.crt", "server-chain.crt",
    "client.key", "client.crt", "client-chain.crt",
)

_FEDERATION_INI_TEMPLATE = """\
# {ansible_managed_hint}
# OTS federation plugin config, generated by ots-federation-quickstart.
# Parsed by ots_federation.config.get_federation_config() on plugin load.
# See README.qmd in the ots-federation-plugin source for the full field
# reference and BYO-CA requirements.

[federation]
enabled = true
server_id = {server_id}
listen_enabled = true
listen_ip = 0.0.0.0
listen_port = {listen_port}
# SECURITY NOTE: accept_as/share_as below are WILDCARD defaults — they admit
# every inbound group (tagged {accept_as_local}) and share every local group
# outbound. This matches the proven fleet default (ansible ots_server role)
# so a freshly quick-started node federates out of the box, but it is
# permissive by design. TIGHTEN to your real ACL group names before adding
# real [federate:*] peers — see README.qmd "CoT Events Not Exchanged".
accept_as = {accept_as}
share_as = {share_as}

[federation_ssl]
fed_ca_bundle = {cert_dir}/fed-ca.crt
fed_cert = {cert_dir}/server-chain.crt
fed_key = {cert_dir}/server.key
fed_verify_hostname = true
"""


def _check_ots_environment():
    """
    Verify 'opentakserver' (a hard dependency declared in pyproject.toml) is
    importable in this interpreter.

    ots_federation.plugin itself degrades gracefully when opentakserver is
    absent (falls back to `object` as the plugin base class) so importing it
    is NOT a reliable signal here. Checking opentakserver directly is: if
    this fails, the operator is very likely running this console script from
    the wrong Python/venv, or the wheel was installed with dependency
    resolution skipped (e.g. `pip install --no-deps`) — see README.qmd
    "Plugin Fails to Load" for the resulting OTS-side symptom (PluginManager's
    issubclass(plugin_class, Plugin) check fails).
    """
    try:
        import opentakserver  # noqa: F401
        return True
    except ImportError:
        return False


def _detect_ots_install(ots_config_path):
    """
    Best-effort, non-fatal detection of an OTS install at ots_config_path.
    Never edits the file — only informs the operator whether
    OTS_FEDERATION_CONFIG needs to be added there.
    """
    if not os.path.isfile(ots_config_path):
        print(
            f"[ots-federation-quickstart] WARNING: OTS config not found at "
            f"{ots_config_path} (override with --ots-config). Continuing — "
            "this check is informational only.",
            file=sys.stderr,
        )
        return
    print(f"[ots-federation-quickstart] Found OTS config: {ots_config_path}")
    try:
        with open(ots_config_path, "r") as f:
            contents = f.read()
    except OSError as exc:
        print(f"[ots-federation-quickstart] WARNING: could not read {ots_config_path}: {exc}", file=sys.stderr)
        return
    if "OTS_FEDERATION_CONFIG" not in contents:
        print(
            "[ots-federation-quickstart] NOTE: OTS_FEDERATION_CONFIG is not set in "
            f"{ots_config_path}. Add it manually (this script never edits your OTS "
            "config) pointing at the federation.ini path printed below."
        )


def _existing_outputs(cert_dir, ini_path, export_dir):
    """Return the list of paths that already exist and would be clobbered."""
    hits = []
    for fname in _GENERATE_OUTPUT_FILES:
        p = os.path.join(cert_dir, fname)
        if os.path.exists(p):
            hits.append(p)
    if os.path.exists(ini_path):
        hits.append(ini_path)
    if os.path.isdir(export_dir) and os.listdir(export_dir):
        hits.append(export_dir)
    return hits


def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    parser = argparse.ArgumentParser(
        prog="ots-federation-quickstart",
        description=(
            "Quick-start OTS federation on a stock OpenTAKServer install: "
            "generate a federation CA + server/client identity, write a "
            "minimal federation.ini, and emit the mutual-CA peer-exchange "
            "bundle. PRECONDITION: the ots-federation wheel is already "
            "pip-installed into the OTS venv — that install is what makes "
            "this console script exist; its first executable step is "
            "certificate generation, not the pip install."
        ),
    )
    parser.add_argument(
        "--ots-config", default=DEFAULT_OTS_CONFIG,
        help=f"Path to the OTS config.yml, for install detection only (default: {DEFAULT_OTS_CONFIG}).",
    )
    parser.add_argument(
        "--cert-dir", default=DEFAULT_CERT_DIR,
        help=f"Directory to write generated cert material (default: {DEFAULT_CERT_DIR}).",
    )
    parser.add_argument(
        "--ini-path", default=DEFAULT_INI_PATH,
        help=f"Path to write federation.ini (default: {DEFAULT_INI_PATH}).",
    )
    parser.add_argument(
        "--export-dir", default=None,
        help="Directory to write the peer-exchange bundle (default: <cert-dir>/export-bundle).",
    )
    parser.add_argument(
        "--server-id", default=None,
        help="This server's federation server_id (default: local hostname).",
    )
    parser.add_argument(
        "--server-address", default=None,
        help="This server's reachable hostname/IP — used as the cert SAN and the "
             "export bundle's address field (default: local FQDN).",
    )
    parser.add_argument(
        "--listen-port", type=int, default=DEFAULT_LISTEN_PORT,
        help=f"Federation inbound listen_port (default: {DEFAULT_LISTEN_PORT}).",
    )
    parser.add_argument(
        "--accept-as", default=DEFAULT_ACCEPT_AS,
        help=f"Global [federation] accept_as (default: {DEFAULT_ACCEPT_AS!r} — wildcard, see security note).",
    )
    parser.add_argument(
        "--share-as", default=DEFAULT_SHARE_AS,
        help=f"Global [federation] share_as (default: {DEFAULT_SHARE_AS!r} — wildcard, see security note).",
    )
    parser.add_argument(
        "--force", action="store_true",
        help="Overwrite existing cert material / federation.ini / export bundle.",
    )
    args = parser.parse_args(argv)

    if not _check_ots_environment():
        print(
            "[ots-federation-quickstart] ERROR: 'opentakserver' is not importable in this "
            "Python environment.",
            file=sys.stderr,
        )
        print(
            "[ots-federation-quickstart] This usually means you are not running inside the "
            "OTS venv, or the wheel was installed without resolving its dependencies. Fix:",
            file=sys.stderr,
        )
        print(
            "  source /opt/opentakserver/venv/bin/activate && pip install ots_federation-<version>-py3-none-any.whl",
            file=sys.stderr,
        )
        return 1

    _detect_ots_install(args.ots_config)

    server_id = args.server_id or socket.gethostname()
    server_address = args.server_address or socket.getfqdn()
    cert_dir = os.path.abspath(args.cert_dir)
    ini_path = os.path.abspath(args.ini_path)
    export_dir = os.path.abspath(args.export_dir) if args.export_dir else os.path.join(cert_dir, "export-bundle")

    existing = _existing_outputs(cert_dir, ini_path, export_dir)
    if existing and not args.force:
        print(
            "[ots-federation-quickstart] ERROR: existing federation output found; refusing to "
            "clobber without --force:",
            file=sys.stderr,
        )
        for p in existing:
            print(f"  {p}", file=sys.stderr)
        return 1

    os.makedirs(cert_dir, exist_ok=True)
    os.makedirs(os.path.dirname(ini_path) or ".", exist_ok=True)

    print(
        f"[ots-federation-quickstart] server_id={server_id} address={server_address} "
        f"listen_port={args.listen_port}"
    )

    # 1. Certs: CA + SAN-correct server/client identity + chain.
    ret = cmd_generate(
        [
            "--out-dir", cert_dir,
            "--ca-cn", f"{server_id}-fed-ca",
            "--server-cn", server_id,
            "--client-cn", f"{server_id}-client",
            "--server-san-dns", server_address,
        ],
        prog="ots-federation-quickstart (generate)",
    )
    if ret != 0:
        return ret

    # 2. Minimal federation.ini.
    ini_text = _FEDERATION_INI_TEMPLATE.format(
        ansible_managed_hint="Generated by ots-federation-quickstart -- hand-edit freely; not ansible-managed.",
        server_id=server_id,
        listen_port=args.listen_port,
        accept_as=args.accept_as,
        accept_as_local=(args.accept_as.split(":")[-1] or "(strip)"),
        share_as=args.share_as,
        cert_dir=cert_dir,
    )
    fd = os.open(ini_path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o644)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(ini_text)
    except Exception:
        os.close(fd)
        raise
    print(f"[ots-federation-quickstart] Wrote {ini_path}")

    # 3. Peer-exchange bundle (mutual-CA exchange).
    ret = cmd_export(
        [
            "--cert-dir", cert_dir,
            "--out-dir", export_dir,
            "--server-id", server_id,
            "--our-address", server_address,
            "--listen-port", str(args.listen_port),
        ],
        prog="ots-federation-quickstart (export)",
    )
    if ret != 0:
        return ret

    print()
    print("[ots-federation-quickstart] Done. Set OTS_FEDERATION_CONFIG to:")
    print(f"  {ini_path}")
    print("[ots-federation-quickstart] then restart OTS to activate federation:")
    print("  sudo systemctl restart opentakserver")
    print(f"[ots-federation-quickstart] Peer-exchange bundle ready to hand out: {export_dir}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
